version: '3.8'

services:
        
 wordpress:
   image: wordpress
   environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: MYSQL_USER
     WORDPRESS_DB_PASSWORD: MYSQL_PASSWORD
     WORDPRESS_DB_NAME: MYSQL_DATABASE
   restart: always
   volumes:
     - wordpress:/var/www/html
   ports:
     - 80:80
   depends_on:
     - db

 db:
   container_name: db      
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
     MYSQL_DATABASE: MYSQL_DATABASE
     MYSQL_USER: MYSQL_USER
     MYSQL_PASSWORD: MYSQL_PASSWORD
   restart: always
   volumes:
     - db:/var/lib/mysql
 
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   environment:
     PMA_HOST: db
   restart: always
   ports:
     - '8081:80'
   depends_on:
     - db    

volumes:
  wordpress:
  db:
